USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS RETAIL_CUSTOMER_360
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Customer 360 & Loyalty — Retail/CPG Demo (Snowflake + Amazon Bedrock + SES + QuickSight)';

CREATE SCHEMA IF NOT EXISTS RETAIL_CUSTOMER_360.RAW DATA_RETENTION_TIME_IN_DAYS = 3;
CREATE SCHEMA IF NOT EXISTS RETAIL_CUSTOMER_360.CURATED DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA IF NOT EXISTS RETAIL_CUSTOMER_360.AI DATA_RETENTION_TIME_IN_DAYS = 14;
CREATE SCHEMA IF NOT EXISTS RETAIL_CUSTOMER_360.ML DATA_RETENTION_TIME_IN_DAYS = 14;
CREATE SCHEMA IF NOT EXISTS RETAIL_CUSTOMER_360.SEARCH;
CREATE SCHEMA IF NOT EXISTS RETAIL_CUSTOMER_360.APP;

CREATE WAREHOUSE IF NOT EXISTS WH_CUSTOMER_360
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Customer 360 & Loyalty demo workloads';
