USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_CUSTOMER_360;
USE WAREHOUSE WH_CUSTOMER_360;

CREATE NETWORK RULE IF NOT EXISTS RETAIL_CUSTOMER_360.AI.BEDROCK_NETWORK_RULE
    TYPE = HOST_PORT MODE = EGRESS VALUE_LIST = ('bedrock-runtime.us-west-2.amazonaws.com:443');

CREATE SECRET IF NOT EXISTS RETAIL_CUSTOMER_360.AI.BEDROCK_SECRET
    TYPE = GENERIC_STRING SECRET_STRING = '{}';

CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS RETAIL_C360_BEDROCK_EAI
    ALLOWED_NETWORK_RULES = (RETAIL_CUSTOMER_360.AI.BEDROCK_NETWORK_RULE)
    ALLOWED_AUTHENTICATION_SECRETS = (RETAIL_CUSTOMER_360.AI.BEDROCK_SECRET)
    ENABLED = TRUE
    COMMENT = 'External Access Integration for Amazon Bedrock (Customer 360 - personalized NBA)';

CREATE NETWORK RULE IF NOT EXISTS RETAIL_CUSTOMER_360.AI.SES_NETWORK_RULE
    TYPE = HOST_PORT MODE = EGRESS VALUE_LIST = ('email.us-west-2.amazonaws.com:443');

CREATE SECRET IF NOT EXISTS RETAIL_CUSTOMER_360.AI.SES_SECRET
    TYPE = GENERIC_STRING SECRET_STRING = '{}';

CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS RETAIL_C360_SES_EAI
    ALLOWED_NETWORK_RULES = (RETAIL_CUSTOMER_360.AI.SES_NETWORK_RULE)
    ALLOWED_AUTHENTICATION_SECRETS = (RETAIL_CUSTOMER_360.AI.SES_SECRET)
    ENABLED = TRUE
    COMMENT = 'External Access Integration for Amazon SES (Customer 360 - churn re-engagement emails)';
